# Generated by Django 3.2.13 on 2022-06-04 17:30

import cuentas.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('dni', models.CharField(max_length=150, unique=True, verbose_name='DNI')),
                ('complete_name', models.CharField(max_length=150, verbose_name='complete name')),
                ('is_player', models.BooleanField(default=True, help_text='Designates the user is player.', verbose_name='is player')),
                ('is_owner', models.BooleanField(default=False, help_text='Designates the user is an establishment owner.', verbose_name='is owner')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'cuentas_usuario',
            },
            managers=[
                ('objects', cuentas.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PerfilPropietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_propietario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cuentas_perfil_propietario',
            },
        ),
        migrations.CreateModel(
            name='PerfilJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_jugador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cuentas_perfil_jugador',
            },
        ),
    ]
